name: dswitch
version: 5.3.2
homepage: https://dswitch.onepub.dev
documentation: https://dswitch.onepub.dev
description: DSwitch is a cli tool that allows you to rapidly switch between channels and versions of Dart. You can also pin a channel to a specific version.
repository: https://github.com/onepub-dev/dswitch
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  archive: ^3.3.8
  args: ^2.1.1
  dcli: ^3.3.4
  dcli_core: ^3.3.4
  meta: ^1.0.0
  path: ^1.0.0
  pub_semver: ^2.0.0
  pubspec_manager: ^1.0.0-alpha.14
  scope: ^4.0.1
  settings_yaml: ^8.0.1
  system_info2: ^4.0.0
  win32: ^4.1.4
dev_dependencies: 
  lint_hard: ^4.0.0
  mocktail: ^1.0.2
  test: ^1.15.0
executables: 
  dswitch: 
  dswitch_install: 
